server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?serverTimezone=UTC
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      initial-size: 20
      min-idle: 10
      max-active: 100


---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8002

person:
  name: rao

---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8001

person:
  name: hu
---
person:
  name: lin
server:
  port: 8009
spring:
  config:
    activate:
      on-profile: prod